# main.yml
name: deploy blog
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Change base directory
        run: cd website

      - name: Install dependencies
        run: yarn install

      - name: Build docs
        run: yarn build

      - name: Deploy by ssh
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "website/docs/.vuepress/dist/"
          REMOTE_HOST: "47.106.202.255"
          REMOTE_USER: "root"
          TARGET: "/home/blog-deploy"
